// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SahibindenClone.Infrastructure.Context;

#nullable disable

namespace SahibindenClone.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("SahibindenClone.Domain.Entities.Advert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("CityId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CityId");

                    b.HasIndex("UserId");

                    b.ToTable("Adverts");
                });

            modelBuilder.Entity("SahibindenClone.Domain.Entities.AdvertImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AdvertId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMain")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AdvertId");

                    b.ToTable("AdvertImages");
                });

            modelBuilder.Entity("SahibindenClone.Domain.Entities.AdminAuditLog", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<string>("Action").IsRequired().HasColumnType("TEXT");
                    b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                    b.Property<string>("Details").IsRequired().HasColumnType("TEXT");
                    b.Property<bool>("IsActive").HasColumnType("INTEGER");
                    b.Property<int>("AdminUserId").HasColumnType("INTEGER");
                    b.Property<int>("TargetId").HasColumnType("INTEGER");
                    b.Property<string>("TargetType").IsRequired().HasColumnType("TEXT");
                    b.Property<DateTime?>("UpdatedAt").HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("AdminUserId");
                    b.ToTable("AdminAuditLogs");
                });

            modelBuilder.Entity("SahibindenClone.Domain.Entities.AdvertChangeHistory", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<int>("AdvertId").HasColumnType("INTEGER");
                    b.Property<int>("ChangedByUserId").HasColumnType("INTEGER");
                    b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                    b.Property<bool>("IsActive").HasColumnType("INTEGER");
                    b.Property<string>("NewDescription").IsRequired().HasColumnType("TEXT");
                    b.Property<decimal>("NewPrice").HasColumnType("TEXT");
                    b.Property<string>("NewTitle").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("PreviousDescription").IsRequired().HasColumnType("TEXT");
                    b.Property<decimal>("PreviousPrice").HasColumnType("TEXT");
                    b.Property<string>("PreviousTitle").IsRequired().HasColumnType("TEXT");
                    b.Property<DateTime?>("UpdatedAt").HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("AdvertId");
                    b.HasIndex("ChangedByUserId");
                    b.ToTable("AdvertChangeHistories");
                });

            modelBuilder.Entity("SahibindenClone.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("SahibindenClone.Domain.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("SahibindenClone.Domain.Entities.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AdvertId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AdvertId");

                    b.HasIndex("UserId", "AdvertId")
                        .IsUnique();

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("SahibindenClone.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RelatedLink")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("SahibindenClone.Domain.Entities.PurchaseTransaction", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<int>("AdvertId").HasColumnType("INTEGER");
                    b.Property<int>("BuyerId").HasColumnType("INTEGER");
                    b.Property<DateTime?>("CompletedAt").HasColumnType("TEXT");
                    b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                    b.Property<bool>("IsActive").HasColumnType("INTEGER");
                    b.Property<int>("SellerId").HasColumnType("INTEGER");
                    b.Property<int>("Status").HasColumnType("INTEGER");
                    b.Property<DateTime?>("UpdatedAt").HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("BuyerId");
                    b.HasIndex("SellerId");
                    b.ToTable("PurchaseTransactions");
                });

            modelBuilder.Entity("SahibindenClone.Domain.Entities.SellerReview", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<string>("Comment").IsRequired().HasColumnType("TEXT");
                    b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                    b.Property<bool>("IsActive").HasColumnType("INTEGER");
                    b.Property<int>("PurchaseTransactionId").HasColumnType("INTEGER");
                    b.Property<int>("Rating").HasColumnType("INTEGER");
                    b.Property<int>("ReviewerId").HasColumnType("INTEGER");
                    b.Property<int>("SellerId").HasColumnType("INTEGER");
                    b.Property<DateTime?>("UpdatedAt").HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("PurchaseTransactionId").IsUnique();
                    b.HasIndex("ReviewerId");
                    b.HasIndex("SellerId");
                    b.HasIndex("PurchaseTransactionId", "ReviewerId").IsUnique();
                    b.ToTable("SellerReviews");
                });

            modelBuilder.Entity("SahibindenClone.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("User");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SahibindenClone.Domain.Entities.Advert", b =>
                {
                    b.HasOne("SahibindenClone.Domain.Entities.Category", "Category")
                        .WithMany("Adverts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SahibindenClone.Domain.Entities.City", "City")
                        .WithMany("Adverts")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SahibindenClone.Domain.Entities.User", "User")
                        .WithMany("Adverts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("City");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SahibindenClone.Domain.Entities.AdvertImage", b =>
                {
                    b.HasOne("SahibindenClone.Domain.Entities.Advert", "Advert")
                        .WithMany("Images")
                        .HasForeignKey("AdvertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Advert");
                });

            modelBuilder.Entity("SahibindenClone.Domain.Entities.AdminAuditLog", b =>
                {
                    b.HasOne("SahibindenClone.Domain.Entities.User", "AdminUser")
                        .WithMany().HasForeignKey("AdminUserId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.Navigation("AdminUser");
                });

            modelBuilder.Entity("SahibindenClone.Domain.Entities.AdvertChangeHistory", b =>
                {
                    b.HasOne("SahibindenClone.Domain.Entities.Advert", "Advert")
                        .WithMany().HasForeignKey("AdvertId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("SahibindenClone.Domain.Entities.User", "ChangedByUser")
                        .WithMany().HasForeignKey("ChangedByUserId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.Navigation("Advert");
                    b.Navigation("ChangedByUser");
                });

            modelBuilder.Entity("SahibindenClone.Domain.Entities.Category", b =>
                {
                    b.HasOne("SahibindenClone.Domain.Entities.Category", "Parent")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("SahibindenClone.Domain.Entities.Favorite", b =>
                {
                    b.HasOne("SahibindenClone.Domain.Entities.Advert", "Advert")
                        .WithMany("Favorites")
                        .HasForeignKey("AdvertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SahibindenClone.Domain.Entities.User", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Advert");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SahibindenClone.Domain.Entities.Notification", b =>
                {
                    b.HasOne("SahibindenClone.Domain.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SahibindenClone.Domain.Entities.PurchaseTransaction", b =>
                {
                    b.HasOne("SahibindenClone.Domain.Entities.Advert", "Advert")
                        .WithMany().HasForeignKey("AdvertId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.HasOne("SahibindenClone.Domain.Entities.User", "Buyer")
                        .WithMany().HasForeignKey("BuyerId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.HasOne("SahibindenClone.Domain.Entities.User", "Seller")
                        .WithMany().HasForeignKey("SellerId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.Navigation("Advert");
                    b.Navigation("Buyer");
                    b.Navigation("Seller");
                    b.Navigation("Review");
                });

            modelBuilder.Entity("SahibindenClone.Domain.Entities.SellerReview", b =>
                {
                    b.HasOne("SahibindenClone.Domain.Entities.PurchaseTransaction", "PurchaseTransaction")
                        .WithOne("Review").HasForeignKey("SahibindenClone.Domain.Entities.SellerReview", "PurchaseTransactionId")
                        .OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.HasOne("SahibindenClone.Domain.Entities.User", "Reviewer")
                        .WithMany().HasForeignKey("ReviewerId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.HasOne("SahibindenClone.Domain.Entities.User", "Seller")
                        .WithMany().HasForeignKey("SellerId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.Navigation("PurchaseTransaction");
                    b.Navigation("Reviewer");
                    b.Navigation("Seller");
                });

            modelBuilder.Entity("SahibindenClone.Domain.Entities.Advert", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("SahibindenClone.Domain.Entities.Category", b =>
                {
                    b.Navigation("Adverts");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("SahibindenClone.Domain.Entities.City", b =>
                {
                    b.Navigation("Adverts");
                });

            modelBuilder.Entity("SahibindenClone.Domain.Entities.User", b =>
                {
                    b.Navigation("Adverts");

                    b.Navigation("Favorites");

                    b.Navigation("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
